[programs.localnet]
mysolanaapp = "GgqJotJyRR4QQF12h2gKLi8hWyiRhKNFmnBkFtuEpJ9p"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/micheal/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
