[package]
name = "criterion_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.1"

[[bench]]
name = "fibonacci"
harness = false

[dependencies]
